security:
  # Step 1: Define Role Hierarchy
  role_hierarchy:
    ROLE_ADMIN: [ROLE_USER, ROLE_MODERATOR]

  # Step 2: Define User Provider
  providers:
    in_memory:
      memory:
        users:
          admin:
            password: "$2y$12$4PZw5dQZCnO9cFEftZw5V.pUm9Ov.I8.A5SkJ7F6iXoRROxHkPO4W" # bcrypt hashed password
            roles: ["ROLE_ADMIN"]

  # Step 3: Configure Firewalls
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      anonymous: true
      provider: in_memory
      form_login:
        login_path: login
        check_path: login
      logout:
        path: /logout
        target: /

  # Step 4: Set Access Control Rules
  access_control:
    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/, roles: ROLE_USER }
